name: .NET Test

on:
  workflow_call:
    inputs:
      projects:
        description: Optional path to the project(s) file to build. Supports globbing. Default is an empty string.
        required: false
        type: string
        default: ''
      configuration:
        description: Defines the build configuration. Default is Release (to reduce risk of surprises when transitioning to Production).
        required: false
        type: string
        default: 'Release'
      runs-on:
        description: The type of machine to run the job on. Default is ubuntu-24.04.
        required: false
        type: string
        default: 'ubuntu-24.04'
      include-preview:
        description: When set to true, includes preview versions of .NET. Default is false.
        required: false
        type: boolean
        default: false
      verbosity-level:
        description: Sets the verbosity level of the command. Allowed values are quiet, minimal, normal, detailed, and diagnostic. Default is quiet.
        required: false
        type: string
        default: 'quiet'
      coverage-report-folder-name:
        description: The name of the folder where the coverage report will be written. Default is Coverage.
        required: false
        type: string
        default: 'Coverage'
      test-results-folder-name:
        description: The name of the folder where the test results will be written. Default is TestResults.
        required: false
        type: string
        default: 'TestResults'
      build:
        description: Whether to build the project(s) before testing. Default is false.
        required: false
        type: boolean
        default: false
      build-switches:
        description: Provides a way to fully customize the build. Default is an empty string. See https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#switches for more information.
        required: false
        type: string
        default: ''
      restore:
        description: Whether to restore the project(s) before testing. Default is false.
        required: false
        type: boolean
        default: false
      restore-cache-key:
        description: When set, the current workspace will be overwritten with the content of the restore cache. Default is an empty string.
        required: false
        type: string
        default: ''
      blame-hang-timeout:
        description: The time to wait for a test to complete before collecting a dump. Default is 10 minutes.
        required: false
        type: string
        default: '10m'
      blame-hang-dump-type:
        description: The type of dump to collect when a test hangs. Default is mini.
        required: false
        type: string
        default: 'mini'
      test-arguments:
        description: Additional arguments to pass to the test runner. Default is an empty string.
        required: false
        type: string
        default: ''
      timeout-minutes:
        description: The maximum time in minutes to allow the job to run. Default is 15 minutes.
        required: false
        type: number
        default: 15

jobs:
  test:
    name: 🧪 Test
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: codebeltnet/git-checkout@v1

      - name: Install .NET
        uses: codebeltnet/install-dotnet@v2
        with:
          includePreview: ${{ inputs.include-preview }}

      - name: Install .NET Tool - Report Generator
        uses: codebeltnet/dotnet-tool-install-reportgenerator@v1

      - if: inputs.restore-cache-key != ''
        name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/.git
            ~/.nuget/packages
          key: ${{ inputs.restore-cache-key }}
          restore-keys: |
            dotnet-restore-
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-${{ inputs.configuration }}'
          merge-multiple: true

      - if: inputs.restore
        name: Restore Dependencies
        uses: codebeltnet/dotnet-restore@v3
        with:
          projects: ${{ inputs.projects }}
          verbosity-level: ${{ inputs.verbosity-level }}
    
      - if: inputs.build
        name: Build with ${{ inputs.configuration }} configuration
        uses: codebeltnet/dotnet-build@v4
        with:
          projects: ${{ inputs.projects }}
          configuration: ${{ inputs.configuration }}
          verbosity-level: ${{ inputs.verbosity-level }}
          build-switches: ${{ inputs.build-switches }}

      - name: Test with ${{ inputs.configuration }} build
        uses: codebeltnet/dotnet-test@v4
        with:
          configuration: ${{ inputs.configuration }}
          projects: ${{ inputs.projects }}
          verbosity-level: ${{ inputs.verbosity-level }}
          test-results-folder-name: ${{ inputs.test-results-folder-name }}
          build-switches: ${{ inputs.build-switches }}
          blame-hang-timeout: ${{ inputs.blame-hang-timeout }}
          blame-hang-dump-type: ${{ inputs.blame-hang-dump-type }}
          test-arguments: ${{ inputs.test-arguments }}
          build: ${{ inputs.build }}
          restore: ${{ inputs.restore }}

      - if: success() && runner.os == 'Linux'
        name: Content of Test Results Folder
        run: ls -R $RUNNER_TEMP/${{ inputs.test-results-folder-name }}

      - if: success() && runner.os == 'Windows'
        name: Content of Test Results Folder
        shell: pwsh
        run: Get-ChildItem -Path "$env:RUNNER_TEMP\${{ inputs.test-results-folder-name }}" -Recurse

      - name: Use Report Generator
        run: reportgenerator "-reports:$RUNNER_TEMP/${{ inputs.test-results-folder-name }}/**/*.opencover.xml" "-targetdir:${{ github.workspace }}/${{ inputs.coverage-report-folder-name }}" "-reporttypes:Cobertura;MarkdownSummaryGithub;HTMLInline;HTMLChart"
        shell: bash

      - name: Write to Job Summary
        if: success() && runner.os == 'Linux'
        run: cat ${{ github.workspace }}/${{ inputs.coverage-report-folder-name }}/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Write to Job Summary
        if: success() && runner.os == 'Windows'
        run: Get-Content ${{ github.workspace }}/${{ inputs.coverage-report-folder-name }}/SummaryGithub.md | Add-Content $env:GITHUB_STEP_SUMMARY
        shell: pwsh

      - name: Upload CoverageReport
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport-${{ inputs.configuration }}-${{ runner.os }}-${{ hashFiles(inputs.projects) }}
          path: ${{ github.workspace }}/${{ inputs.coverage-report-folder-name }}
          include-hidden-files: true

      - name: Upload TestResults
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-${{ inputs.configuration }}-${{ runner.os }}-${{ hashFiles(inputs.projects) }}
          path: ${{ runner.temp }}/${{ inputs.test-results-folder-name }}
          include-hidden-files: true
